server:
  port: 8081

spring:
  application:
    name: principal-producer
  cache:
    type: redis
  redis:
    port: 6379

kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic.request-topic: topic_request_estado
  topic.requestreply-topic: topic_reply_estado
  topic.request-topic-cidade: topic_request_cidade
  topic.requestreply-topic-cidade: topic_reply_cidade
  consumer-group: principal
  producer:
    max:
      request:
        size: 231072080
    batch-size: 60000000
    buffer-memory: 60000000
    bootstrap-servers: 127.0.0.1:9092
    client-id: principal-producer
    consumer:
      group-id: principal
      auto-offset-reset: earliest
      enable-auto-commit: false
  